//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounterTactics.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App_pl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_pl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CounterTactics.Client.Resources.App.pl-PL", typeof(App_pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Działania.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kurs.
        /// </summary>
        public static string AddClass {
            get {
                return ResourceManager.GetString("AddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wydział.
        /// </summary>
        public static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć obiektu.
        /// </summary>
        public static string AddFailure {
            get {
                return ResourceManager.GetString("AddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiekt został pomyślnie utworzony.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj prowadzącego.
        /// </summary>
        public static string AddTeacher {
            get {
                return ResourceManager.GetString("AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularz dodawania nowego prowadzącego.
        /// </summary>
        public static string AddTeacherForm {
            get {
                return ResourceManager.GetString("AddTeacherForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel administratora.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursy.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź usunięcie obiektu.
        /// </summary>
        public static string ConfirmObjectDeletion {
            get {
                return ResourceManager.GetString("ConfirmObjectDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się pobrać danych z serwera.
        /// </summary>
        public static string CouldNotRetrieveDataFromServer {
            get {
                return ResourceManager.GetString("CouldNotRetrieveDataFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecna nazwa kursu.
        /// </summary>
        public static string CurrentClassName {
            get {
                return ResourceManager.GetString("CurrentClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecne dane.
        /// </summary>
        public static string CurrentData {
            get {
                return ResourceManager.GetString("CurrentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zaktualizować danych.
        /// </summary>
        public static string DataUpdateFailure {
            get {
                return ResourceManager.GetString("DataUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane zostały poprawnie zaktualizowane.
        /// </summary>
        public static string DataUpdateSuccess {
            get {
                return ResourceManager.GetString("DataUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopień.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulowano usunięcie obiektu.
        /// </summary>
        public static string DeletionCancelled {
            get {
                return ResourceManager.GetString("DeletionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak przy usuwaniu obiektu.
        /// </summary>
        public static string DeletionFailed {
            get {
                return ResourceManager.GetString("DeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiekt został usunięty.
        /// </summary>
        public static string DeletionSuccess {
            get {
                return ResourceManager.GetString("DeletionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytowanie kursu.
        /// </summary>
        public static string EditClass {
            get {
                return ResourceManager.GetString("EditClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytowanie wydziału.
        /// </summary>
        public static string EditFaculty {
            get {
                return ResourceManager.GetString("EditFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytowanie prowadzącego.
        /// </summary>
        public static string EditTeacher {
            get {
                return ResourceManager.GetString("EditTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydziały.
        /// </summary>
        public static string Faculties {
            get {
                return ResourceManager.GetString("Faculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jest wymagane.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jest wymagana.
        /// </summary>
        public static string IsRequiredFemine {
            get {
                return ResourceManager.GetString("IsRequiredFemine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jest wymagany.
        /// </summary>
        public static string IsRequiredMasculine {
            get {
                return ResourceManager.GetString("IsRequiredMasculine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalogowano jako.
        /// </summary>
        public static string LoggedAs {
            get {
                return ResourceManager.GetString("LoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LoginAction {
            get {
                return ResourceManager.GetString("LoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zalogować.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się lub zarejestruj aby kontynuować.
        /// </summary>
        public static string LogOrRegisterToProceed {
            get {
                return ResourceManager.GetString("LogOrRegisterToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna liczba znaków.
        /// </summary>
        public static string MaxCharacterLength {
            get {
                return ResourceManager.GetString("MaxCharacterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna liczba znaków.
        /// </summary>
        public static string MinCharacterLength {
            get {
                return ResourceManager.GetString("MinCharacterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa nazwa kursu.
        /// </summary>
        public static string NewClassName {
            get {
                return ResourceManager.GetString("NewClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak wyników.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi zawierać małą literę, dużą literę, cyfrę oraz znak specjalny.
        /// </summary>
        public static string PasswordRule {
            get {
                return ResourceManager.GetString("PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string RegisterAction {
            get {
                return ResourceManager.GetString("RegisterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja nie powiodła się.
        /// </summary>
        public static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoszenia.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcje.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrót.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdzono.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prowadzący.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zaktualizować obiektu.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga.
        /// </summary>
        public static string WarningCaution {
            get {
                return ResourceManager.GetString("WarningCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj na CounterTactics.
        /// </summary>
        public static string WelcomeOnPolWro {
            get {
                return ResourceManager.GetString("WelcomeOnPolWro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o tej nazwie już istnieje.
        /// </summary>
        public static string WithThisNameAlreadyExists {
            get {
                return ResourceManager.GetString("WithThisNameAlreadyExists", resourceCulture);
            }
        }
    }
}
